export const SSSL_SAMPLE = 'SSSL_SAMPLE';

export const APP_IS_LOADING = 'APP_IS_LOADING';
export const CLEAR_LOADING = 'CLEAR_LOADING';

export const QUERIES_LOADED = 'QUERIES_LOADED';
export const SINGLE_QUERY_LOADED = 'SINGLE_QUERY_LOADED';

export const EVENTS_LOADED = 'EVENTS_LOADED';
export const SINGLE_EVENT_LOADED = 'SINGLE_EVENT_LOADED';